In [1]:
import numpy as np;
import pandas as pd;

In [3]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': [
        'East', 'West', 'North', 'South', 'East',
        'West', 'North', 'South', 'East', 'West',
        'North', 'South', 'East', 'West', 'North',
        'South', 'East', 'West', 'North', 'South'
    ],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': [
        'John', 'Mary', 'Bob', 'Alice', 'John',
        'Mary', 'Bob', 'Alice', 'John', 'Mary',
        'Bob', 'Alice', 'John', 'Mary', 'Bob',
        'Alice', 'John', 'Mary', 'Bob', 'Alice'
    ]
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [5]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    186     70   John  January      Q1
1  2023-01-02       B   West    893     43   Mary  January      Q1
2  2023-01-03       C  North    318     24    Bob  January      Q1
3  2023-01-04       D  South    790     92  Alice  January      Q1
4  2023-01-05       A   East    783     29   John  January      Q1
5  2023-01-06       B   West    946     89   Mary  January      Q1
6  2023-01-07       C  North    838     91    Bob  January      Q1
7  2023-01-08       D  South    905     15  Alice  January      Q1
8  2023-01-09       A   East    869     43   John  January      Q1
9  2023-01-10       B   West    275     57   Mary  January      Q1
10 2023-01-11       C  North    803     67    Bob  January      Q1
11 2023-01-12       D  South    368     10  Alice  January      Q1
12 2023-01-13       A   East    534     20   John  January      Q1
13 2023-01-14       B   West    626     54   Mary  January      Q1
14 2023-01-15       C  North    943     15    Bob  January      Q1
15 2023-01-16       D  South    745     39  Alice  January      Q1
16 2023-01-17       A   East    865     50   John  January      Q1
17 2023-01-18       B   West    273     82   Mary  January      Q1
18 2023-01-19       C  North    864     33    Bob  January      Q1
19 2023-01-20       D  South    841     12  Alice  January      Q1

In [ ]:
pivot = pd.pivot_table(df, values="Sales", index= "Region" , columns= "Product" , aggfunc="median");

## values must be numeric;

pivot

Product      A      B      C      D
Region
East     783.0    NaN    NaN    NaN
North      NaN    NaN  838.0    NaN
South      NaN    NaN    NaN  790.0
West       NaN  626.0    NaN    NaN

### Cross Tabs

In [ ]:
pd.crosstab(df['Region'] , df['Product'])

## Cross Tabs gives the count of the items.

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0